#!/bin/bash
# Generates the effective Odoo configuration from config/odoo.conf and the
# environment, then hands over to the official image entrypoint.
#
# Values written here (addons_path, admin_passwd, db_*) are only added when
# config/odoo.conf does not already define them, so the file always wins.

set -euo pipefail

BASE_CONF=/etc/odoo/odoo.base.conf
TARGET_CONF="${ODOO_RC:-/etc/odoo/odoo.conf}"

# Mount points, in the order they should appear in addons_path.
ADDONS_ROOTS=(/mnt/enterprise-addons /mnt/third-party-addons /mnt/custom-addons)

log() { echo "[odoo-docker] $*" >&2; }
trap 'log "ERROR: entrypoint failed at line $LINENO"' ERR

# A directory is an addons directory when one of its children is a module.
is_addons_dir() {
    compgen -G "$1/*/__manifest__.py" > /dev/null
}

collect_addons_paths() {
    local root sub
    for root in "${ADDONS_ROOTS[@]}"; do
        [ -d "$root" ] || continue
        if is_addons_dir "$root"; then
            echo "$root"
        fi
        # Also accept one level of repositories, e.g. third_party/<oca-repo>/<module>.
        for sub in "$root"/*/; do
            sub="${sub%/}"
            if [ -d "$sub" ] && [ ! -f "$sub/__manifest__.py" ] && is_addons_dir "$sub"; then
                echo "$sub"
            fi
        done
    done
    return 0
}

warn_on_suspicious_enterprise() {
    local dir=/mnt/enterprise-addons
    if [ -f "$dir/base/__manifest__.py" ] || [ -f "$dir/web/__manifest__.py" ]; then
        log "WARNING: addons/enterprise contains 'base' or 'web'. It looks like a full"
        log "WARNING: Odoo source tree, not the odoo/enterprise repository. Community"
        log "WARNING: modules from the image may be shadowed by a different version."
    fi
}

has_option() {
    [ -f "$BASE_CONF" ] && grep -qE "^\s*$1\s*=" "$BASE_CONF"
}

build_config() {
    local generated=() addons_path

    if ! has_option addons_path; then
        addons_path="$(collect_addons_paths | paste -sd, -)"
        if [ -n "$addons_path" ]; then
            generated+=("addons_path = $addons_path")
        fi
        log "addons_path: ${addons_path:-<community modules only>}"
    fi
    has_option admin_passwd || generated+=("admin_passwd = ${ADMIN_PASSWORD:-admin}")
    has_option db_host      || generated+=("db_host = ${DB_HOST:-db}")
    has_option db_port      || generated+=("db_port = ${DB_PORT:-5432}")
    has_option db_user      || generated+=("db_user = ${POSTGRES_USER:-odoo}")
    has_option db_password  || generated+=("db_password = ${POSTGRES_PASSWORD:-odoo}")

    local extra
    extra="$(printf '%s\n' "${generated[@]}")"

    {
        echo "; Generated by odoo-docker at container start. Edit config/odoo.conf instead."
        if [ -f "$BASE_CONF" ]; then
            # Insert generated options right after the [options] header.
            # ENVIRON is used instead of -v so the multi-line value is passed verbatim.
            EXTRA="$extra" awk '
                { sub(/\r$/, "") }
                { print }
                /^\[options\]/ && !done { print ENVIRON["EXTRA"]; done = 1 }
                END { if (!done) { print "[options]"; print ENVIRON["EXTRA"] } }
            ' "$BASE_CONF"
        else
            echo "[options]"
            echo "$extra"
        fi
    } > "$TARGET_CONF"
}

# Used by the odoo-docker helper to pick up addons folders created after start.
if [ "${1:-}" = "--configure-only" ]; then
    build_config
    exit 0
fi

warn_on_suspicious_enterprise
build_config

# Enable developer mode for the main server process only.
if [ "$#" -eq 1 ] && [ "$1" = "odoo" ] && [ -n "${ODOO_DEV_MODE:-}" ]; then
    set -- odoo "--dev=${ODOO_DEV_MODE}"
fi

exec /entrypoint.sh "$@"
